name: Build SwiftUI SPM Project

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.8'

      - name: Resolve Swift Packages
        run: swift package resolve

      - name: Build Project
        run: swift build

      - name: Run SwiftUI Entry
        run: swift run
